version: '3.1'
services:
    ci:
        image: php:7.2-cli
        container_name: ci
        entrypoint:
            - bash
            - check_standard
        working_dir: "/var/www"
        volumes:
            - .:/var/www