version: '3.1'
services:
    ci:
        image: dockercraft/php
        container_name:  test
        entrypoint:
            - bash
            - check_standard
        working_dir: "/var/www"
        volumes:
            - .:/var/www
            - ./php.ini:/etc/php7/conf.d/90-customization.ini

    composer:
        image: dockercraft/composer
        container_name: composer
        entrypoint:
            - composer
        command: "-v"
        working_dir: "/var/www"
        volumes:
            - .:/var/www